/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_wniemiec_cheat_ptanks_PocketTanksAccessor */

#ifndef _Included_com_wniemiec_cheat_ptanks_PocketTanksAccessor
#define _Included_com_wniemiec_cheat_ptanks_PocketTanksAccessor
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getWindVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_openProcess
        (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getWindVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_closeProcess
        (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getWindVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_accessPlayerOne
        (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getWindVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_accessPlayerTwo
        (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getTankPositionX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_getTankPositionX
  (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getTankPositionY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_getTankPositionY
  (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getTankPower
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_getTankPower
  (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getTankAngle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_getTankAngle
  (JNIEnv *, jclass);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    setTankPositionX
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_setTankPositionX
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    setTankPositionY
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_setTankPositionY
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    setTankPower
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_setTankPower
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    setTankAngle
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_setTankAngle
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_wniemiec_cheat_ptanks_PocketTanksAccessor
 * Method:    getWindVariable
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_wniemiec_cheat_ptanks_PocketTanksAccessor_getWindValue
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
